<div class="container">
  <span>account</span>
  <div class="errorBlock"></div>
  <form action="php-backend/login-script.php" method="POST">
    <div class="row">
      <input type="text" name="usermail" class="inputField" placeholder="Username or E-mail">
    </div>
    <div class="row">
      <input type="password" name="passwd" class="inputField" placeholder="Password">
    </div>
    <div class="rowSmaller">
      <input type="checkbox" name="rememPasswd">
      <span>Keep logged</span>
    </div>
    <div class="row">
      <button type="submit" name="login-submit" class="loginButton">Log in</button>
      <a href="?page=register"><button type="button" class="regButton">Register</button></a>
    </div>
  </form>
</div>