<main>
  <div class="logo noselect">
    <span>Kitcat<i>Tube</i></span>
  </div>
  <div class="content">
    <h1>Terms of Use</h1>

    <div>
      <ol>
        <li>Example 1
          <ol>
            <li>Point 1</li>
            <li>Point 2</li>
            <li>Point 3
              <ol>
                <li>Subpoint 1</li>
                <li>Subpoint 2</li>
                <li>Subpoint 3</li>

              </ol>
            </li>
          </ol>
        </li>
        <li>Example 2
          <ol>
            <li>Point 1</li>
            <li>Point 2</li>
            <li>Point 3
              <ol>
                <li>Subpoint 1</li>
                <li>Subpoint 2</li>
                <li>Subpoint 3</li>

              </ol>
            </li>
          </ol>
        </li>
        <li>Example 3
          <ol>
            <li>Point 1</li>
            <li>Point 2</li>
            <li>Point 3
              <ol>
                <li>Subpoint 1</li>
                <li>Subpoint 2</li>
                <li>Subpoint 3</li>

              </ol>
            </li>
          </ol>
        </li>
        <li>Example 4
          <ol>
            <li>Point 1</li>
            <li>Point 2</li>
            <li>Point 3</li>
          </ol>
        </li>
      </ol>
    </div>

  </div>
</main>
